# Generated by Django 4.1.3 on 2022-12-15 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='desc',
            new_name='desc1',
        ),
        migrations.AlterField(
            model_name='place',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
