# Generated by Django 4.1.3 on 2022-12-15 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelapp', '0002_rename_desc_place_desc1_alter_place_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Place1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('img', models.ImageField(upload_to='pics')),
                ('desc1', models.TextField()),
            ],
        ),
        migrations.RenameField(
            model_name='place',
            old_name='desc1',
            new_name='desc',
        ),
        migrations.AlterField(
            model_name='place',
            name='name',
            field=models.CharField(max_length=250),
        ),
    ]
