# Generated by Django 4.1.3 on 2022-12-20 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotelapp', '0003_place1_rename_desc1_place_desc_alter_place_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Place1',
            new_name='Team',
        ),
    ]
