# Generated by Django 4.1.3 on 2022-12-21 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelapp', '0004_rename_place1_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(max_length=150),
        ),
    ]
